/* common */
ATTR2(none,0)
ATTR2(any,1)
ATTR(id)
ATTR(label)
ATTR(country_all)
ATTR(country_iso3)
ATTR(country_iso2)
ATTR(country_car)
ATTR(country_name)
ATTR(town_name)
ATTR(district_name)
ATTR(street_name)
ATTR(street_name_systematic)
ATTR(limit)
ATTR(type)
ATTR(debug)
ATTR(address)
ATTR(phone)
ATTR(entry_fee)
ATTR(open_hours)
/* town */
ATTR(size)
/* poi */
ATTR(icon)
ATTR(info_html)
ATTR(price_html)
