/* prototypes */
enum projection;
struct color;
struct coord;
struct displaylist;
struct gui;
struct layout;
struct mapset;
struct navit;
struct point;
struct route;
struct transformation;
struct vehicle;
void navit_add_mapset(struct navit *this, struct mapset *ms);
struct mapset *navit_get_mapset(struct navit *this);
void navit_add_layout(struct navit *this, struct layout *lay);
void navit_draw(struct navit *this);
void navit_zoom_in(struct navit *this, int factor);
void navit_zoom_out(struct navit *this, int factor);
struct navit *navit_new(const char *ui, const char *graphics, struct coord *center, enum projection pro, int zoom);
void navit_init(struct navit *this);
void navit_set_center(struct navit *this, struct coord *center);
void navit_set_center_screen(struct navit *this, struct point *p);
void navit_toggle_cursor(struct navit *this);
void navit_vehicle_add(struct navit *this, struct vehicle *v, struct color *c, int update, int follow);
struct gui *navit_get_gui(struct navit *this);
struct transformation *navit_get_trans(struct navit *this);
struct route *navit_get_route(struct navit *this);
struct displaylist *navit_get_displaylist(struct navit *this);
void navit_destroy(struct navit *this);
